<?php
/**
 * Mindarc Pty Ltd.
 *
 * @category    Mindarc
 * @package     Mindarc_GoogleFeed
 * @author      Mindarc Team <hello@mindarc.com.au>
 * @copyright   Copyright (c) 2019 Mindarc Pty Ltd. (https://www.mindarc.com.au/)
 */
?>
<?php
$viewModel = $block->getData('viewModel');
$xml = $viewModel->getFeed();
?>
<div class="feed-preview-container">
    <div class="page-main-actions">
        <div class="page-actions">
            <div class="page-actions-inner" data-title="Edit Store">
                <div class="page-actions-buttons">
                    <button id="back" title="Back" type="button" class="action-default scalable back" onclick="setLocation('<?= $viewModel->getBackUrl() ?>')">
                        <span>Back</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class='steps-wizard'>
            <div class="steps-wizard-section col-6">
                <div class="steps-wizard-section-title">
                    <span><?= __('URL of the Google feed file:') ?></span>
                </div>

                <?php if ($xml): ?>
                    <p><a href="<?= $viewModel->getFeedUrl() ?>" target="_blank"><?= $viewModel->getFeedUrl() ?></a></p>
                <?php else: ?>
                    <p><?= __('No feed file or URL found for this profile. Generate the feed and check again.') ?></p>
                <?php endif; ?>
            </div>

            <?php if ($xml): ?>
                <div class="steps-wizard-section col-6">
                    <div class="steps-wizard-section-title">
                        <span><?= __('Feed file preview (sample):') ?></span>
                    </div>
                    <div>
                        <pre class="noformat" style="border: 1px solid #CCCCCC; padding: 10px; color: #FFFFFF; background: #403934;">
                            <code class="html"></code>
                        </pre>
                    </div>
                </div>
                <script>
                    require([
                        'jquery',
                    ], function ($) {
                        var xmlformatter = {
                            /**
                             * https://gist.github.com/sente/1083506/d2834134cd070dbcc08bf42ee27dabb746a1c54d
                             *
                             * @param xml
                             * @returns {string}
                             */
                            format: function (xml) {
                                var formatted = '';
                                var reg = /(>)(<)(\/*)/g;
                                xml = xml.replace(reg, '$1\r\n$2$3');
                                var pad = 0;
                                $.each(xml.split('\r\n'), function (index, node) {
                                    var indent = 0;
                                    if (node.match(/.+<\/\w[^>]*>$/)) {
                                        indent = 0;
                                    } else if (node.match(/^<\/\w/)) {
                                        if (pad != 0) {
                                            pad -= 1;
                                        }
                                    } else if (node.match(/^<\w[^>]*[^\/]>.*$/)) {
                                        indent = 1;
                                    } else {
                                        indent = 0;
                                    }

                                    var padding = '';
                                    for (var i = 0; i < pad; i++) {
                                        padding += '  ';
                                    }

                                    formatted += padding + node + '\r\n';
                                    pad += indent;
                                });

                                return formatted;
                            }
                        };
                        var xmlString = "<?= $xml ?>";
                        var formattedXml = xmlformatter.format(xmlString);
                        var xmlEscaped = formattedXml.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/ /g, '&nbsp;').replace(/~~/g, '<br/>');

                        $('pre code.html').html(xmlEscaped + '</br>...');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
</div>